nav:
  logo: "https://telegraph-image-aog.pages.dev/file/50c69527e9570de90e5cf.jpg"
  display_title: true
  fixed: false # fixed navigation bar

menu:
  首頁: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# aside (側邊欄)
# --------------------------------------
aside:
  enable: true
  hide: false
  button: true
  mobile: false # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Github 主页
      link: https://github.com/allinu

theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"

top_img: "https://telegraph-image-aog.pages.dev/file/62a4c1face05fdb53db10.jpg"
default_top_img: "https://telegraph-image-aog.pages.dev/file/62a4c1face05fdb53db10.jpg"
footer_bg: "#FAB4C5"

custom_text: 向前，向前，一直向前！

# fancybox http://fancyapps.com/fancybox/3/
fancybox: true

subtitle:
  enable: false
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  # loop (循環打字)
  loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  # source: false
  source: 1
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  # sub:
  #   - 今日事&#44;今日畢
  #   - Never put off till tomorrow what you can do today

# 加載動畫 Loading Animation
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 1
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url:

# https://github.com/vinta/pangu.js
# Insert a space between Chinese character and English character (中英文之間添加空格)
pangu:
  enable: false
  field: post # site/post

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: giscus
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: true # Display comment count in Home Page

# Giscus
# https://giscus.app/
giscus:
  repo: allinu/comments
  repo_id: MDEwOlJlcG9zaXRvcnkzNjY5MjIwNzQ=
  category_id: DIC_kwDOFd7JWs4CTncW
  theme: 
    light: light
    dark: dark
  option:
    data-mapping: title
    data-input-position: top
    data-strict: 0

local_search:
  enable: true
  preload: true
  field: all
  content: true
  CDN:

mathjax:
  enable: true
  # true 表示每一頁都加載mathjax.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
  per_page: false

mermaid:
  enable: true
  # built-in themes: default/forest/dark/neutral
  theme:
    light: default
    dark: dark

baidu_analytics: 2c508a859a285e2d4b81680167c94c9d
google_analytics: 3330885346

avatar:
  img: "https://telegraph-image-aog.pages.dev/file/50c69527e9570de90e5cf.jpg"
  effect: false # 頭像會一直轉圈

index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover: "https://telegraph-image-aog.pages.dev/file/9b3347aaa90ea80e57c94.jpg"

copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

reward:
  enable: true
  QR_code:
    - img: /img/wx.jpg
      link:
      text: 微信
    - img: /img/zfb.jpg
      link:
      text: 支付宝

noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
  message_prev: 距离上次更新已经过了
  message_next: 天了，内容可能有所过时，请谨慎参考

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

runtimeshow:
  enable: true
  publish_date: 1/1/2020 00:00:00  
  ##網頁開通時間
  #格式: 月/日/年 時間
  #也可以寫成 年/月/日 時間

newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # unit: mins, save data to localStorage
  avatar: true

highlight_theme: mac
highlight_height_limit: 200

social:
  fab fa-telegram: https://t.me/hacker_videos || Telegram
  fab fa-github: https://github.com/allinu || Github
  fas fa-envelope: mailto:lionacc@163.com || Email

# A simple 404 page
error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background: "https://telegraph-image-aog.pages.dev/file/85c72fc101747c7d2e48d.png"